### ISSUE TITLE
Remove/Updated Deprecated Rules

### ISSUE THREAD

**Issue by mthomes** [manovotny/stylelint-config-get-off-my-lawn#3]
Deprecated rules need updated in the config. Some may need replaced with a plugin ([declaration-block-properties-order](https://github.com/stylelint/stylelint/issues/2035)).

See this [stylelint issue 2123](https://github.com/stylelint/stylelint/issues/2123) for more info

**Comment by manovotny** [comment]
This is fixed by PR #6 and will be released as a part of the `v2.0.0` milestone.
